FROM nvidia/cuda:12.2.0-runtime-ubuntu20.04
FROM python:3.11

ARG FACEFUSION_VERSION=1.1.0

ENV GRADIO_SERVER_NAME=0.0.0.0
WORKDIR /facefusion

RUN apt-get update
RUN apt-get install -y ffmpeg

RUN git clone https://github.com/facefusion/facefusion.git --branch $FACEFUSION_VERSION .
RUN pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu118
RUN pip uninstall onnxruntime
RUN pip install onnxruntime-gpu==1.15.1
